#!/usr/bin/env php
<?php
require_once (__DIR__ . "/find-autoloader.php");
ini_set("memory_limit", "256M");

$scope = APP_CORE_NAME;

try {
    $databaseConfigs = $scope::Container()->get(\Gone\AppCore\DbConfig::class);
}catch(\Gone\AppCore\Exceptions\DbConfigException $dbConfigException){
    $databaseConfigs = null;
}

$laminator = new \⌬\Database\Laminator(
    $rootOfApp,
    $databaseConfigs
);
$laminator->cleanCodePHPCSFixer();