#!/usr/bin/env php
<?php

require_once (__DIR__ . "/find-autoloader.php");

ini_set("memory_limit", "256M");

$sdkOutputPath = isset($argv[1]) ? $argv[1] : APP_ROOT . "/vendor/gone.io/lib" . strtolower(APP_NAME) . "/";
$appName       = isset($argv[2]) ? $argv[2] : null;
$remoteApiUri  = isset($argv[3]) ? $argv[3] : null;
$namespace     = isset($argv[4]) ? $argv[4] : "Gone";

define("APP_NAMESPACE", $namespace);

try {
    $databaseConfigs = $scope::Container()->get(\Gone\AppCore\DbConfig::class);
}catch(\Gone\AppCore\Exceptions\DbConfigException $dbConfigException){
    $databaseConfigs = null;
}

$zenderator = new \⌬\Database\Zenderator(
    $rootOfApp,
    $databaseConfigs
);

$zenderator->runSdkifier($sdkOutputPath, $remoteApiUri);
